#!/usr/bin/env bash

# shellcheck source=/dev/null
source "./.github/workflows/scripts/e2e-verify.common.sh"

go env -w GOFLAGS=-mod=mod

# verify_provenance_content verifies provenance content generated by the generic generator.
verify_provenance_content() {
    ATTESTATION=$(jq -r '.payload' <"$PROVENANCE" | base64 -d)
    has_assets=$(echo "$THIS_FILE" | cut -d '.' -f5 | grep assets)
    is_goreleaser=$(echo "$THIS_FILE" | cut -d '.' -f5 | grep goreleaser)
    annotated_tags=$(echo "$THIS_FILE" | cut -d '.' -f5 | grep annotated || true)

    echo "  **** Provenance content verification *****"

    # Verify all common provenance fields.
    e2e_verify_common_all "$ATTESTATION"

    e2e_verify_predicate_subject_name "$ATTESTATION" "$BINARY"
    e2e_verify_predicate_builder_id "$ATTESTATION" "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/heads/main"
    e2e_verify_predicate_buildType "$ATTESTATION" "https://github.com/slsa-framework/slsa-github-generator/generic@v1"

    # Ignore tha annotated tags, because they are not part of a release.
    if [[ "$GITHUB_REF_TYPE" == "tag" ]] && [[ -z "$annotated_tags" ]]; then
        assets=$(e2e_get_release_assets_filenames "$GITHUB_REF_NAME")
        if [[ -z "$has_assets" ]]; then
            e2e_assert_eq "$assets" "[\"null\",\"null\"]" "there should be no assets"
        else
            if [[ -n "$is_goreleaser" ]]; then
                if ! assert_not_empty "$assets" "there should be assets"; then
                    exit 1
                fi
            else
                multi_subjects=$(echo "$THIS_FILE" | cut -d '.' -f5 | grep multi-subjects)
                if [[ -n "$multi_subjects" ]]; then
                    e2e_assert_eq "$assets" "[\"multiple.intoto.jsonl\",\"null\"]" "there should be assets"
                else
                    e2e_assert_eq "$assets" "[\"hello.intoto.jsonl\",\"null\"]" "there should be assets"
                fi
            fi
        fi
    fi
}

THIS_FILE=$(e2e_this_file)
BRANCH=$(echo "$THIS_FILE" | cut -d '.' -f4)
echo "branch is $BRANCH"
echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
echo "GITHUB_REF: $GITHUB_REF"
echo "DEBUG: file is $THIS_FILE"

export SLSA_VERIFIER_TESTING="true"

# Verify provenance authenticity.
e2e_run_verifier_all_releases "v1.1.0"

# Verify the provenance content.
verify_provenance_content
