#!/usr/bin/env bash

# shellcheck source=/dev/null
source "./.github/workflows/scripts/e2e-verify.common.sh"

# Script Inputs
GITHUB_REF=${GITHUB_REF:-}
GITHUB_REF_NAME=${GITHUB_REF_NAME:-}
GITHUB_REF_TYPE=${GITHUB_REF_TYPE:-}
BINARY=${BINARY:-}
PROVENANCE=${PROVENANCE:-}
BUILDER_ID=${BUILDER_ID:-}
BUILDER_TAG=${BUILDER_TAG:-}
CHECKOUT_SHA1=${CHECKOUT_SHA1:-}
CHECKOUT_MESSAGE=${CHECKOUT_MESSAGE:-}

RUNNER_DEBUG=${RUNNER_DEBUG:-}
if [[ -n "${RUNNER_DEBUG}" ]]; then
    set -x
fi

go env -w GOFLAGS=-mod=mod

# verify_provenance_content verifies provenance content generated by the container generator.
verify_provenance_content() {
    attestation=$(jq -r '.dsseEnvelope.payload' <"$PROVENANCE" | base64 -d)

    echo "  **** Provenance content verification *****"

    # Verify all common provenance fields.
    e2e_verify_common_all_v1 "${attestation}"

    e2e_verify_predicate_subject_name "${attestation}" "$BINARY"
    e2e_verify_predicate_v1_runDetails_builder_id "${attestation}" "${BUILDER_ID}@refs/tags/${BUILDER_TAG}"
    e2e_verify_predicate_v1_buildDefinition_buildType "${attestation}" "https://github.com/slsa-framework/slsa-github-generator/delegator-generic@v0"

    # Verify the artifact contains the expected value.
    if [[ -n ${CHECKOUT_SHA1} ]]; then
        cat <"${BINARY}" | grep "${CHECKOUT_MESSAGE}" || exit 1
    fi
}

this_file=$(e2e_this_file)
this_branch=$(echo "${this_file}" | cut -d '.' -f4)
echo "branch is ${this_branch}"
echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
echo "GITHUB_REF: $GITHUB_REF"
echo "DEBUG: file is ${this_file}"

export SLSA_VERIFIER_TESTING="true"

# Verify provenance authenticity.
# TODO(233): Update to v1.8.0 tag.
e2e_run_verifier_all_releases "HEAD"

# Verify provenance content.
verify_provenance_content
