name: Build using github-actions-demo
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: bazelisk build //:hello
      - uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: bazel-bin/hello_/hello
          output_path: hello.provenance
        continue-on-error: true
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: |
            bazel-bin/hello_/hello
            hello.provenance
