name: yamllint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  # Needed to check out the repo.
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - env:
          YAMLLINT_VERSION: "1.26.3"
        run: |
          set -euo pipefail

          # Install yamllint
          pip install "yamllint==${YAMLLINT_VERSION}"

          # Run yamllint
          make yamllint
